server:
  port: 9091
spring:
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/salesteam?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
      username: root
      password: 123456
      #filters: stat,wall,log4j,config #配置监控统计拦截的filter，去掉stat，wall，log4j，config
      max-active: 100             #最大连接数
      initial-size: 1             #初始化大小
      max-wait: 60000             #获取连接等待超时时间
      min-idle: 1                 #最小连接数
      time-between-eviction-runs-millis: 60000    #间隔多久进行一次检测，检测需关闭的空闲连接，单位毫秒
      min-evictable-idle-time-millis: 30000       #一个连接在池中最小生存的时间，单位是毫秒
      validation-query: select 'x'                #
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20

#
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: 123456
#    url: jdbc:mysql://localhost:3306/salesteam?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
